import React from 'react'
import Register from './Register'
import Login from './Login'
import Home1 from './Home1'
import Yc from './Yc'
import Yf from './Yf'
import Ys from './Ys'
import Contact from './Contact'
import Forgetpass1 from './Forgetpass/Forgetpass1'
import Forgetpass2 from './Forgetpass/Forgetpass2'
import Forgetpass3 from './Forgetpass/Forgetpass3'
import YSform from '../components/YSform'
import Footer from './Footer'
import Profile from './Profile'
import Yogaprofile from './Yogaprofile'
import Box2 from '../components/Box2'
import Box3 from '../components/Box3'
import Admin from './Admin'
import Admin2 from './Admin2'
import AdminTeacher from './AdminTeacher'
import Sessionstudinfo from '../components/Sessionstudinfo'
import AddStud from '../components/AddStud'
import Instrustors from './Instrustors'
import YCform1 from './YCforms/YCform1'
import YCform from '../components/YCform'
import YCform10 from './YCforms/YCform10'
import YCform2 from './YCforms/YCform2'
import YCform3 from './YCforms/YCform3'
import YCform4 from './YCforms/YCform4'
import YCform5 from './YCforms/YCform5'
import YCform6 from './YCforms/YCform6'
import YCform7 from './YCforms/YCform7'
import YCform8 from './YCforms/YCform8'
import YCform9 from './YCforms/YCform9'
import YSform1 from './YSforms/YSform1'
import YSform2 from './YSforms/YSform2'
import YSform3 from './YSforms/YSform3'
import YSform4 from './YSforms/YSform4'
import YSform5 from './YSforms/YSform5'
import YSform6 from './YSforms/YSform6'
import YSform7 from './YSforms/YSform7'
import YSform8 from './YSforms/YSform8'
import YCapplication from '../components/YCapplication'
import PGDYT from './YCapplications/PGDYT'
import PGDAV from './YCapplications/PGDAV'
import PGDYEd from './YCapplications/PGDYEd'
import PMIC from './YCapplications/PMIC'
import AVTC from './YCapplications/AVTC'
import DYEd from './YCapplications/DYEd'
import RPL from './YCapplications/RPL'
import TTCAshtanga from './YCapplications/TTCAshtanga'
import TTCHata from './YCapplications/TTCHata'
import YIC from './YCapplications/YIC'
import Studcoursecard from '../components/Studcoursecard'
import Uploadimg from '../components/Uploadimg'
import Logincard from '../components/Logincard'

function Demo() {
  return (
    <>
<Admin2/>
    </>
  )
}

export default Demo
